# {{ package_name }}

FROM srcd/lookout-sdk-ml:0.12.1

WORKDIR /analyzers
COPY requirements.txt .

RUN apt-get update && \
    apt-get install -y --no-install-suggests --no-install-recommends \
      postgresql-client python3-dev gcc g++ {{ pkg }} {{ pkg_dev }} && \
    pip3 install --no-cache-dir -r requirements.txt && \
    apt-get remove -y python3-dev gcc g++ {{ pkg_dev }} && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY . .
CMD ["run", "{{ analyzers }}", "-c", "analyzers.yml"]
